os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10.1
install: swift package update
script:
  - swift build
  - swift test
notifications:
  email:
    on_success: never
    on_failure: change